config/routes.rb
Adoptajerry::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  use_doorkeeper
  mount API::Base => '/api'
  constraints CanAccessAPIDocumentation do
    mount GrapeSwaggerRails::Engine => '/api-doc'
  end

  devise_for :makers
  root 'jerries#index'

  get "/build" => 'pages#start'
  get '/auth/:provider/callback' => 'omniauth_callbacks#create'
  get '/signout' => 'sessions#destroy'
  get 'makers/profile' => 'makers#edit', as: :edit_profile
  patch 'makers/profile' => 'makers#update', as: :profile
  get 'makers/:id' => 'makers#show', as: :maker
  get 'jerries/roulette' => 'jerries#roulette', as: :jerry_roulette
  get 'jerries/:id/team/edit' => 'jerries#edit_team', as: :edit_team

  resources :jerries do
    resources :organs
  end

  resources :pages, only: :show

  get "makers/locale/:name" => 'makers#locale', as: :save_locale
  resources :locales, controller: :translations, only: :show

  # tiny API to get an access_token for the main API
  namespace :api, format: :json do
    namespace :v1 do
      resources :makers do
        collection do
          get :me
        end
      end
    end
  end

end

app/models/jerry.rb
class Jerry < ActiveRecord::Base
  has_paper_trail
  acts_as_commentable

  has_many :organs, dependent: :destroy
  validates_associated :organs
  accepts_nested_attributes_for :organs, allow_destroy: true

  has_many :skills, dependent: :destroy
  validates_associated :skills
  accepts_nested_attributes_for :skills, allow_destroy: true

  has_many :pictures, dependent: :destroy

  has_and_belongs_to_many :makers

  validates :name, presence: true, length: {minimum: 3}, uniqueness: true
  mount_uploader :avatar, AvatarUploader
end

app/controllers/jerries_controller.rb
require Rails.root.join('app/interactions/jerries/create_jerry')
require Rails.root.join('app/interactions/jerries/update_jerry')

class JerriesController < ApplicationController
  before_action :find_jerry, except: [:new, :create, :index, :roulette]
  before_action :authenticate_maker!, except: [:index, :show, :roulette]
  before_action :check_maker_clearance, only: [:edit, :update, :edit_team]

  def new
    @jerry = Jerry.new
    @jerry.organs.build
    @jerry.skills.build
    @jerry.pictures.build
  end

  def create
    images = if params[:jerry][:pictures].present?
               params[:jerry][:pictures][:image]
             else
               []
             end
    outcome = CreateJerry.run(
      params: params[:jerry],
      maker: current_maker,
      images: images)

    if outcome.valid?
      redirect_to jerry_path outcome.result
    else
      @jerry = outcome.result
      render :new
    end
  end

  def show
  end

  def index
  end

  def edit
  end

  def update
    update_team
    images = if params[:jerry][:pictures].present?
               params[:jerry][:pictures][:image]
             else
               []
             end

    outcome = UpdateJerry.run(
      jerry: @jerry,
      params: params[:jerry],
      images: images)

    if outcome.valid?
      redirect_to jerry_path outcome.result
    else
      @jerry = outcome.result || @jerry
      render :edit
    end
  end

  def destroy
    @jerry.destroy
    redirect_to jerries_path
  end

  def edit_team
  end

  def roulette
    rand_id = Jerry.ids.shuffle.first
    @jerry = Jerry.find(rand_id)
    redirect_to @jerry
  end

  private

  def find_jerry
    @jerry = Jerry.find params[:id]
  end

  def check_maker_clearance
    unless @jerry.makers.include? current_maker
      redirect_to @jerry, notice: 'You can not edit this Jerry'
    end
  end

  def update_team
    if params[:jerry][:makers]
      new_maker = Maker.find_by email: params[:jerry][:makers][:uid]
      if new_maker
        @jerry.makers << new_maker
      else
        flash.now.notice = "Unknown maker '#{params[:jerry][:makers][:uid]}', can not be added to the team"
      end
    end
  end

end

app/helpers/jerries_helper.rb
module JerriesHelper
end

app/views/jerries/_form.html.slim
= simple_nested_form_for @jerry do |f|

  .row
    .col-md-12 ng-controller="TabsCtrl"

      = f.error_notification

      tabset
        tab active="tabs[0].active"
          tab-heading
            | {{'jerry_form.steps.first.short' | translate}}
          h3
            | {{'jerry_form.steps.first.long' | translate}}

          = f.input :name, placeholder: "Jerry Khan"
          = f.input :bio, placeholder: "Born to conquer the digital divides"
          = f.input :location, placeholder: "Lomé, Togo"

          .row
            .col-md-3
              - if @jerry.avatar?
                = image_tag @jerry.avatar.url(:medium).to_s, class: 'img-responsive'
              - else
                = image_tag "http://placehold.it/300x300&text=#{@jerry.name ? @jerry.name : "Jerry picture"}", class: "img-responsive"
            .col-md-9
              = f.input :avatar

          hr

          .row
            .col-md-12
              .profile-panel

                h4
                  | {{'pictures' | translate | capitalize}}

                div ng-controller="GalleryCtrl"
                  - if @jerry.pictures.count > 0
                    div
                      | {{'click_on_a_picture_to_delete_it' | translate}}
                  span ng-repeat="picture in pictures"
                    img ng-src="{{picture.image.small.url}}" ng-click="delete(picture)" tooltip="Click to delete" tooltip-trigger="mouseenter"

                h5
                  | {{'add_pictures' | translate}}

                = f.label :pictures, "You can select multiple pictures at once by holding the Ctrl key"
                = f.fields_for :pictures do |p|
                  = p.file_field :image, multiple: true, class: 'button small radius'

          .pull-right

            button.btn.btn-default.btn-sm type="button" ng-click="tabs[1].active = true"
              | {{'next' | translate | capitalize}}

        tab active="tabs[1].active"
          tab-heading
            | {{'jerry_form.steps.second.short' | translate}}
          h3
            | {{'jerry_form.steps.second.long' | translate}}

          .profile-panel

            h4
              | {{'what_is_the_hardware_configuration' | translate | capitalize}}

            = f.fields_for :organs do |organ_form|
              = render 'organs/fields', f: organ_form

            = f.link_to_add "|+| #{t('js.add_an_organ')}", :organs, class: "btn btn-link"

          = f.input :organs_improvment

          .pull-left

            button.btn.btn-default.btn-sm type="button" ng-click="tabs[0].active = true"
              | {{'previous' | translate | capitalize}}

          .pull-right

            button.btn.btn-default.btn-sm type="button" ng-click="tabs[2].active = true"
              | {{'next' | translate | capitalize}}

        tab active="tabs[2].active"
          tab-heading
            | {{'jerry_form.steps.three.short' | translate}}
          h3
            | {{'jerry_form.steps.three.long' | translate}}

          .profile-panel

            h4
              | {{'what_is_the_software_configuration' | translate | capitalize}}

            = f.fields_for :skills do |skills_form|
              = render 'skills/fields', f: skills_form

            = f.link_to_add "|+| #{t('js.add_a_skill')}", :skills, class: "btn btn-link"

          = f.input :skills_improvment

          .pull-left

            button.btn.btn-default.btn-sm type="button" ng-click="tabs[1].active = true"
              | {{'previous' | translate | capitalize}}

          .pull-right

            button.btn.btn-default.btn-sm type="button" ng-click="tabs[3].active = true"
              | {{'next' | translate | capitalize}}

        tab active="tabs[3].active"
          tab-heading
            | {{'jerry_form.steps.fourth.short' | translate}}
          h3
            | {{'jerry_form.steps.fourth.long' | translate}}

          = f.input :mission

          .pull-left

            button.btn.btn-default.btn-sm type="button" ng-click="tabs[2].active = true"
              | {{'previous' | translate | capitalize}}

          .pull-right

            = f.submit class: 'btn btn-default'

app/views/jerries/edit.html.slim
.col-md-8.col-md-offset-2

  h1
    | {{'edit' | translate | capitalize}}
    = " "
    = @jerry.name

  = render 'form'

app/views/jerries/edit_team.html.slim
.col-md-8.col-md-offset-2

  h1
    | {{'contributors_to' | translate}}
    = " "
    = @jerry.name

  - @jerry.makers.each do |maker|
    = link_to "+#{maker.name}", maker_path(maker), class: 'label radius secondary'

  = nested_form_for(@jerry, html: {class: 'new_maker'}) do |f|
    = f.fields_for :makers do |maker_f|
      = maker_f.label :new_maker
      br
      = maker_f.text_field :uid, placeholder: "email"

    .submit
      = f.submit t('js.add_to_the_team'), class: "btn btn-default btn-sm"

app/views/jerries/index.html.slim
section#fold.text-center

  img.img-responsive src="/welcome_to_jerry.gif" alt=t('js.welcome_img_alt')

  .row
    .col-md-4
      .text-center.text-primary
        i.fa.fa-wrench.fa-2x
      .text-justify
        = t('js.presentation.one')
    .col-md-4
      .text-center.text-primary
        i.fa.fa-group.fa-2x
      .text-justify
        = t('js.presentation.two')
    .col-md-4
      .text-center.text-primary
        i.fa.fa-globe.fa-2x
      .text-justify
        = t('js.presentation.three')

section.text-center
  a.btn.btn-default href="#tour"
    | {{'take_the_tour' | translate}}

section.row
  .col-md-8.col-md-offset-2
    #tour.text-center
      .embed-container
        iframe { src="//www.youtube.com/embed/asZ11Nb3Rsg?rel=0"
          frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" }

section#register
  h2.text-center
    | {{'register_your_jerry' | translate}}

  .row
    .col-xs-4.col-xs-offset-4
      .profile
        a href="/jerries/new"
          img.img-responsive src="/add_jerry.png" alt=t('js.add_a_new_jerry')

      .profile-panel
        h5.text-center
          a href="/jerries/new"
            | {{'jerry_etc' | translate}}

section#family.row ng-controller="JerriesCtrl" ng-show="jerries"

  h2.text-center
    | {{'meet_the_family' | translate}}

  div ng-repeat="jerry in jerries | orderBy:'-createdAt'"
    .columns
      .profile
        a ng-href="jerries/{{jerry.id}}"
          div ng-show="jerry.avatar"
            img.img-responsive ng-src="{{jerry.avatar}}" alt="#{t('js.avatar_of')} {{jerry.name}}"
          div ng-hide="jerry.avatar"
            img.img-responsive ng-src="http://placehold.it/300x300&text={{jerry.name}}" alt="#{t('js.avatar_of')} {{jerry.name}}"
      .profile-panel
        h5
          a ng-href="jerries/{{jerry.id}}"
            | {{jerry.name}}
        h6.subheader
          div ng-show="jerry.location"
            | {{'in' | translate}} {{jerry.location}}
          div ng-hide="jerry.location"
            | {{'on_the_internets' | translate}}

app/views/jerries/new.html.slim
.col-md-8.col-md-offset-2

  h1
    | {{'upload_a_new_jerry' | translate}}

  p
    | {{'fill_in_the_birth_certificate_below' | translate}}

  = render 'form'

app/views/jerries/show.html.slim
.row ng-controller="JerriesCtrl"

  .col-md-12

    .row

      .col-md-12

        .pull-right

          - if @jerry.makers.include?(current_maker)
            a.btn.btn-default.btn-sm href="/jerries/#{@jerry.id}/edit"
              | {{'edit_profile' | translate}}

        h1
          = @jerry.name

    .row

      .col-md-4

        .row
          .col-md-12

            - if @jerry.avatar?
              = image_tag @jerry.avatar.url(:medium).to_s, alt: "#{t('js.avatar_of')} #{@jerry.name}", class: 'img-responsive'
            - else
              = image_tag "http://placehold.it/300x300&text=#{@jerry.name}", alt: "#{t('js.avatar_of')} #{@jerry.name}", class: 'img-responsive'

        .row
          .col-md-12
            - if @jerry.location.present?
              h5
                | {{'location' | translate | capitalize}}
                = ": "
                em
                  = @jerry.location

        .row
          .col-md-12

            h5
              | {{'makers' | translate | capitalize}}

            - @jerry.makers.each do |maker|
              = link_to "+#{maker.name}", maker_path(maker), class: "label label-default"

            = " "
            - if @jerry.makers.include?(current_maker)
              a.btn.btn-link href="/jerries/#{@jerry.id}/team/edit"
                | {{'add_a_maker' | translate}}

      .col-md-8

        .row ng-controller="GalleryCtrl"
          .col-md-12
            span ng-repeat="picture in pictures"
              img ng-src="{{picture.image.preview.url}}" ng-click="open('')"

            script id="gallery.html" type="text/ng-template"

              .modal-header
                h3 class="modal-title"
                  | {{'gallery' | translate | capitalize}}

              .modal-body

                div
                  carousel no-wrap="noWrapSlides"
                    slide active="picture.active" ng-repeat="picture in pictures"
                      img ng-src="{{picture.image.large.url}}" style="margin:auto;"

              .modal-footer
                button.btn.btn-default type="button" ng-click="close()"
                  | {{'close' | translate | capitalize}}

        - if @jerry.bio.present?
          .row
            .col-md-12
              h2
                | {{'bio' | translate | capitalize}}
              = simple_format @jerry.bio

        - if @jerry.mission.present?
          .row
            .col-md-12
              h2
                | {{'mission' | translate | capitalize}}
              = simple_format @jerry.mission

        .row
          .col-md-6
            - if @jerry.organs.any?
              h2
                | {{'organs' | translate | capitalize}}
              = render @jerry.organs

            = simple_format @jerry.organs_improvment

          .col-md-6
            - if @jerry.skills.any?
              h2
                | {{'skills' | translate | capitalize}}
              = render @jerry.skills

            = simple_format @jerry.skills_improvment

.row

  .col-md-12

    = render '/shared/timeline'