config/routes.rb
Adoptajerry::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  use_doorkeeper
  mount API::Base => '/api'
  constraints CanAccessAPIDocumentation do
    mount GrapeSwaggerRails::Engine => '/api-doc'
  end

  devise_for :makers
  root 'jerries#index'

  get "/build" => 'pages#start'
  get '/auth/:provider/callback' => 'omniauth_callbacks#create'
  get '/signout' => 'sessions#destroy'
  get 'makers/profile' => 'makers#edit', as: :edit_profile
  patch 'makers/profile' => 'makers#update', as: :profile
  get 'makers/:id' => 'makers#show', as: :maker
  get 'jerries/roulette' => 'jerries#roulette', as: :jerry_roulette
  get 'jerries/:id/team/edit' => 'jerries#edit_team', as: :edit_team

  resources :jerries do
    resources :organs
  end

  resources :pages, only: :show

  get "makers/locale/:name" => 'makers#locale', as: :save_locale
  resources :locales, controller: :translations, only: :show

  # tiny API to get an access_token for the main API
  namespace :api, format: :json do
    namespace :v1 do
      resources :makers do
        collection do
          get :me
        end
      end
    end
  end

end

app/models/maker.rb
class Maker < ActiveRecord::Base
  rolify
  rolify
  has_paper_trail

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :jerries

  validates :name, presence: true
  validates :email, presence: true

  # ------------- Cancan # https://github.com/ryanb/cancan/wiki/ability-for-other-users
  delegate :can?, :cannot?, to: :ability

  def ability
    @ability ||= Ability.new(self)
  end
  # .Cancan

  def locale
    self[:locale] || 'en'
  end

  def self.create_with_omniauth(auth)
    create! do |maker|
      maker.provider = auth[:provider]
      maker.uid = auth[:uid]
      maker.password = Devise.friendly_token[0,20]
      maker.email = auth[:info][:name]
      maker.set_name auth[:info][:name]
    end
  end

  def set_name(email)
    if email
      self.name = email.split('@')[0][0..6] + '-' + rand(36**3).to_s(36)
      #=> 'myname-h9k' if email == 'myname@xmail.com' 
    else
      self.name = rand(36**5).to_s(36)
      #=> 'f8lk2'
    end
  end
end

app/controllers/api/v1/makers_controller.rb
class Api::V1::MakersController < ApplicationController

  def me
    access_token = Doorkeeper::AccessToken.create!(resource_owner_id: current_maker.id,
                                                   expires_in: 20.minutes, scopes: 'public')

    render json: { token: access_token.token }
  end
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController

  def locale
    name = params[:name]
    if @locales.include?(name)
      if maker_signed_in?
        current_maker.locale = name
        current_maker.save
      else
        session[:locale] = name
      end
    end
    redirect_to root_path(changed: true)
  end

  def show
    @maker = Maker.find params[:id]
    @jerries = @maker.jerries
  end
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/views/makers/edit.html.slim
.row
  .col-md-6.col-md-offset-3.col-xs-10.col-xs-offset-1

    h1
      = "Hi #{@maker.name}!"

    = gravatar_tag @maker.uid, size: 50

    p
      | Change your avatar at
      = " "
      = link_to "gravatar.com"

    = simple_form_for @maker, url: edit_profile_path do |f|

      = f.error_notification

      = f.input :name
      = f.input :email
      = f.input :city
      = f.input :bio
      = f.input :twitter_url
      = f.input :website

      = f.button :submit, 'Save', class: 'btn btn-default'

app/views/makers/show.html.slim
.col-md-8.col-md-offset-2

  .profile-panel

    .pull-right
      - if @maker == current_maker
        a.btn.btn-default href="/makers/edit"
          | {{'edit_my_profile' | translate}}

    = gravatar_tag @maker.uid, size: 50, alt: "#{t('js.gravatar_of')} #{@maker.name}"

    p.label.label-default
      = "+#{@maker.name}"

    p
      = "@#{@maker.city}" unless @maker.city.blank?
      - if @maker.bio.present?
        br
        = @maker.bio
        br

      - if @maker.twitter_url?
        | tw:
        = " "
        - if @maker.twitter_url.match(/twitter.com\/(\w*)/)
          = link_to @maker.twitter_url.match(/twitter.com\/(\w*)/)[1], @maker.twitter_url
        br

      - if @maker.website?
        | www:
        = " "
        = link_to @maker.website, @maker.website
        br

      br
      em.text-muted
        | {{'happy_maker_since' | translate}}
        = " #{l(@maker.created_at.to_date, format: :short)}"

  - if @jerries.any?

    h3
      | {{'contributions' | translate | capitalize}}

    - @jerries.each do |jerry|
      p
        - if jerry.avatar.url
          = link_to image_tag(jerry.avatar.url(:small).to_s, alt: "#{t('js.avatar_of')} #{jerry.name}"), jerry_path(jerry)
        - else
          = link_to image_tag("http://placehold.it/50x50&text=#{jerry.name.first.upcase}", alt: "#{t('js.avatar_of')} #{jerry.name}"), jerry_path(jerry)
        = " "
        = link_to jerry.name, jerry_path(jerry)