config/routes.rb
Adoptajerry::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  use_doorkeeper
  mount API::Base => '/api'
  constraints CanAccessAPIDocumentation do
    mount GrapeSwaggerRails::Engine => '/api-doc'
  end

  devise_for :makers
  root 'jerries#index'

  get "/build" => 'pages#start'
  get '/auth/:provider/callback' => 'omniauth_callbacks#create'
  get '/signout' => 'sessions#destroy'
  get 'makers/profile' => 'makers#edit', as: :edit_profile
  patch 'makers/profile' => 'makers#update', as: :profile
  get 'makers/:id' => 'makers#show', as: :maker
  get 'jerries/roulette' => 'jerries#roulette', as: :jerry_roulette
  get 'jerries/:id/team/edit' => 'jerries#edit_team', as: :edit_team

  resources :jerries do
    resources :organs
  end

  resources :pages, only: :show

  get "makers/locale/:name" => 'makers#locale', as: :save_locale
  resources :locales, controller: :translations, only: :show

  # tiny API to get an access_token for the main API
  namespace :api, format: :json do
    namespace :v1 do
      resources :makers do
        collection do
          get :me
        end
      end
    end
  end

end

app/views/layouts/_footer.html.slim
.container
  .row
    .col-md-4.text-left
      | {{'follow' | translate | capitalize}}
      = " "
      a href="http://twitter.com/JerryDIT" target="_blank"
        | {{'jerry_on_twitter' | translate}}
      = " "
      | &amp;
      = " "
      a href="http://www.facebook.com/pages/Jerry-Do-It-Together/518513301524401" target="_blank"
        | {{'on_facebook' | translate}}
    .col-md-8.text-right
      | {{'content' | translate | capitalize}}
      = " "
      a href="http://creativecommons.org/licenses/by-sa/4.0/" target="_blank"
        | {{'cc_by_sa' | translate}}
      = " "
      | {{'jerry_dit_plus' | translate}}
      = " "
      a href="https://github.com/JerryDIT/adoptajerry" target="_blank"
        | {{'source_code' | translate}}
      = " "
      | {{'agplv3' | translate}}
      = " "
      a href="https://groups.google.com/forum/#!forum/techlab-jerrydit" target="_blank"
        | {{'feedback' | translate | translate}}

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String) && msg != "You are not authorized to access this page."
    .alert class="alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-collapse"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/"
        img src="/assets/logo.png" alt="Logo of Jerry" width="28px"
    .collapse.navbar-collapse
      == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
ul.nav.navbar-nav
  li
    a href="/#family"
      | {{'profiles' | translate | capitalize}}
  li
    a href="/jerries/new"
      | {{'add_a_jerry' | translate}}
  li
    a href="/build"
      | {{'build_your_jerry' | translate}}
  li
    a href="http://youandjerrycan.org" target="_blank"
      | {{'about_jerry' | translate}}

ul.nav.navbar-nav.navbar-right
  - if maker_signed_in?
    li
      a href="/makers/#{current_maker.id}"
        | {{'aloha' | translate}} #{current_maker.name}
    li
      a href="/makers/sign_out" data-method='delete'
        | {{'sign_out' | translate}}

  - else
    li
      a href="/makers/sign_in"
        | {{'sign_in' | translate}}
    li
      a href="/makers/sign_up"
        | {{'sign_up' | translate}}

  li.dropdown
    a#languages-dropdown.dropdown-toggle data-toggle="dropdown" href="#"
      = I18n.locale
      span.caret
    ul.dropdown-menu aria-labelledby="languages-dropdown"
      - @locales.each do |locale|
        li
          = link_to locale, save_locale_path(locale), class: "#{"active" if I18n.locale == locale}"

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1" name="viewport"
    base href="/"

    title
      = content_for?(:title) ? yield(:title) : "Adopt a Jerry"

    = favicon_link_tag '/jerry_favicon.ico'
    link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"
    = stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    script src="https://login.persona.org/include.js" type="text/javascript"
    = js_env
    = csrf_meta_tags

  body ng-controller="MainCtrl"
    header#header data-turbolinks-permanent=""
      == render 'layouts/navigation'
    main[role="main"]
      - if ['sessions', 'registrations', 'passwords', 'confirmations', 'unlocks'].include?(controller_name)
        .container
          .row
            .col-md-8.col-md-offset-2
              == render 'layouts/messages'
              == yield
      - else
        .container
          == render 'layouts/messages'
          == yield
      div growl=""
    footer
      == render 'layouts/footer'